export const frenchWordsToGuess = {
  maison: "Bâtiment destiné à l'habitation.",
  chat: "Petit félin domestique.",
  chien: "Animal domestique fidèle à l'homme.",
  arbre: "Grande plante possédant un tronc.",
  eau: "Liquide indispensable à la vie.",
  feu: "Combustion produisant chaleur et lumière.",
  terre: "Sol ou planète où nous vivons.",
  soleil: "Étoile au centre du système solaire.",
  lune: "Satellite naturel de la Terre.",
  ciel: "Espace visible au-dessus de la Terre.",
  mer: "Grande étendue d'eau salée.",
  lac: "Étendue d'eau entourée de terres.",
  riviere: "Cours d'eau naturel.",
  montagne: "Élévation importante du terrain.",
  foret: "Grande zone couverte d'arbres.",
  fleur: "Partie colorée d'une plante.",
  feuille: "Organe généralement vert d'une plante.",
  fruit: "Partie comestible produite par une plante.",
  jardin: "Terrain où poussent plantes et fleurs.",
  herbe: "Plante verte à tige souple.",
  ami: "Personne avec qui l'on entretient une relation d'affection.",
  amour: "Sentiment profond d'attachement.",
  famille: "Ensemble des personnes liées par parenté.",
  pere: "Parent masculin.",
  mere: "Parent féminin.",
  frere: "Enfant masculin des mêmes parents.",
  soeur: "Enfant féminin des mêmes parents.",
  enfant: "Jeune être humain.",
  homme: "Personne adulte de sexe masculin.",
  femme: "Personne adulte de sexe féminin.",
  bebe: "Très jeune enfant.",
  ecole: "Lieu où l'on reçoit un enseignement.",
  eleve: "Personne qui suit un enseignement.",
  maitre: "Personne qui enseigne ou dirige.",
  livre: "Ensemble de pages reliées.",
  cahier: "Recueil de feuilles pour écrire.",
  crayon: "Instrument servant à écrire ou dessiner.",
  stylo: "Instrument d'écriture à encre.",
  lettre: "Caractère de l'alphabet ou message écrit.",
  mot: "Unité de langage.",
  langue: "Système de communication parlé ou écrit.",
  ville: "Grande agglomération urbaine.",
  village: "Petite agglomération rurale.",
  pays: "Territoire formant une nation.",
  route: "Voie permettant de circuler.",
  rue: "Voie publique dans une ville.",
  pont: "Construction permettant de franchir un obstacle.",
  gare: "Lieu de départ et d'arrivée des trains.",
  port: "Lieu d'accueil des bateaux.",
  chambre: "Pièce destinée au repos.",
  cuisine: "Pièce où l'on prépare les repas.",
  salon: "Pièce principale d'une habitation.",
  porte: "Ouverture permettant l'entrée ou la sortie.",
  fenetre: "Ouverture laissant passer lumière et air.",
  mur: "Paroi verticale d'un bâtiment.",
  toit: "Partie supérieure d'un bâtiment.",
  table: "Meuble à surface plane.",
  chaise: "Siège pour une personne.",
  lit: "Meuble destiné au sommeil.",
  lampe: "Objet produisant de la lumière.",
  miroir: "Surface réfléchissante.",
  voiture: "Véhicule routier à moteur.",
  velo: "Véhicule à deux roues actionné par pédales.",
  train: "Moyen de transport ferroviaire.",
  avion: "Appareil permettant de voler.",
  bateau: "Embarcation naviguant sur l'eau.",
  bus: "Véhicule de transport collectif.",
  moto: "Véhicule motorisé à deux roues.",
  roue: "Pièce circulaire permettant le déplacement.",
  moteur: "Machine transformant une énergie en mouvement.",
  travail: "Activité exercée pour produire ou gagner sa vie.",
  argent: "Moyen de paiement.",
  banque: "Établissement financier.",
  marche: "Lieu d'achat et de vente.",
  boutique: "Commerce de détail.",
  bureau: "Lieu de travail administratif.",
  metier: "Profession exercée par une personne.",
  repas: "Moment où l'on mange.",
  pain: "Aliment fabriqué à partir de farine.",
  lait: "Liquide produit par les mammifères.",
  oeuf: "Produit pondu par les oiseaux.",
  viande: "Chair animale consommée comme aliment.",
  poisson: "Animal aquatique à branchies.",
  pomme: "Fruit rond à pépins.",
  poire: "Fruit allongé à chair sucrée.",
  orange: "Agrume de couleur orange.",
  raisin: "Petit fruit poussant en grappes.",
  tomate: "Fruit rouge souvent utilisé comme légume.",
  carotte: "Légume-racine orange.",
  patate: "Tubercule comestible.",
  salade: "Préparation à base de légumes crus.",
  cafe: "Boisson obtenue à partir de grains torréfiés.",
  the: "Boisson obtenue par infusion.",
  musique: "Art de combiner les sons.",
  chanson: "Composition musicale chantée.",
  guitare: "Instrument de musique à cordes.",
  piano: "Instrument à clavier.",
  violon: "Instrument à cordes frottées.",
  danse: "Art du mouvement en rythme.",
  film: "Œuvre cinématographique.",
  image: "Représentation visuelle.",
  photo: "Image obtenue par photographie.",
  dessin: "Représentation réalisée à la main.",
  couleur: "Perception visuelle liée à la lumière.",
  rouge: "Couleur du sang ou du feu.",
  bleu: "Couleur du ciel dégagé.",
  vert: "Couleur de l'herbe.",
  jaune: "Couleur du soleil.",
  noir: "Absence de lumière.",
  blanc: "Couleur de la neige.",
  temps: "Succession des instants.",
  jour: "Période éclairée de la journée.",
  nuit: "Période d'obscurité.",
  matin: "Début de la journée.",
  soir: "Fin de la journée.",
  semaine: "Période de sept jours.",
  mois: "Division de l'année.",
  annee: "Période de douze mois.",
  heure: "Unité de temps de soixante minutes.",
  minute: "Unité de temps de soixante secondes.",
  seconde: "Unité de base du temps.",
  sante: "État physique et mental d'une personne.",
  medecin: "Professionnel de la santé.",
  hopital: "Établissement de soins médicaux.",
  maladie: "Altération de la santé.",
  remede: "Moyen de soigner une maladie.",
  corps: "Ensemble physique d'un être vivant.",
  tete: "Partie supérieure du corps humain.",
  visage: "Partie avant de la tête.",
  oeil: "Organe de la vue.",
  nez: "Organe de l'odorat.",
  bouche: "Ouverture servant à manger et parler.",
  oreille: "Organe de l'audition.",
  main: "Extrémité du bras.",
  bras: "Membre supérieur du corps.",
  jambe: "Membre servant à marcher.",
  pied: "Extrémité inférieure de la jambe.",
  coeur: "Organe qui pompe le sang.",
  esprit: "Faculté de penser et comprendre.",
  idee: "Pensée ou concept.",
  reve: "Suite d'images mentales pendant le sommeil.",
  bonheur: "État de satisfaction durable.",
  joie: "Sentiment de plaisir intense.",
  tristesse: "État émotionnel de chagrin.",
  peur: "Émotion ressentie face à un danger.",
  colere: "Réaction émotionnelle de mécontentement.",
  sourire: "Expression du visage marquant la joie.",
  rire: "Manifestation sonore de l'amusement.",
  jeu: "Activité destinée au divertissement.",
  sport: "Activité physique pratiquée selon des règles.",
  ballon: "Objet sphérique utilisé dans les sports.",
  equipe: "Groupe de personnes agissant ensemble.",
  victoire: "Succès obtenu dans une compétition.",
  defaite: "Perte d'une compétition.",
  nature: "Ensemble des éléments du monde physique.",
  vent: "Déplacement de l'air.",
  pluie: "Précipitation d'eau provenant des nuages.",
  neige: "Précipitation de cristaux de glace.",
  nuage: "Masse visible de vapeur d'eau.",
  orage: "Phénomène météorologique avec éclairs et tonnerre.",
  eclair: "Décharge électrique atmosphérique.",
  pierre: "Morceau de roche.",
  sable: "Ensemble de grains minéraux fins.",
  metal: "Matériau conducteur et solide.",
  or: "Métal précieux jaune.",
  argent: "Métal précieux gris brillant.",
  verre: "Matériau transparent et fragile.",
  bois: "Matière provenant des arbres.",
  papier: "Support utilisé pour écrire ou imprimer.",
  monde: "La Terre et ses habitants.",
  univers: "Ensemble de tout ce qui existe.",
  etoile: "Astre produisant sa propre lumière.",
  planete: "Corps céleste orbitant autour d'une étoile.",
  espace: "Étendue au-delà de l'atmosphère terrestre.",
  science: "Ensemble des connaissances fondées sur l'observation.",
  histoire: "Étude du passé humain.",
  culture: "Ensemble des connaissances et traditions d'un peuple.",
  liberte: "État d'une personne libre d'agir.",
  paix: "Absence de guerre ou de conflit.",
  justice: "Principe d'équité et de droit.",
};

export const englishWordsToGuess = {
  apple: "A round fruit with red, green, or yellow skin.",
  animal: "A living creature that is not a plant.",
  answer: "A response to a question.",
  area: "A particular region or space.",
  arm: "A body part from the shoulder to the hand.",
  baby: "A very young child.",
  back: "The rear part of the body.",
  ball: "A round object used in games.",
  bank: "A place where money is kept and managed.",
  bed: "A piece of furniture for sleeping.",
  bird: "An animal with feathers and wings.",
  book: "A collection of written pages.",
  box: "A container with flat sides.",
  boy: "A male child.",
  bread: "A baked food made from flour.",
  bridge: "A structure built over an obstacle.",
  brother: "A male sibling.",
  car: "A road vehicle with four wheels.",
  card: "A piece of thick paper or plastic.",
  care: "Attention given to someone or something.",
  case: "A particular situation or container.",
  cat: "A small domesticated feline.",
  chair: "A seat for one person.",
  child: "A young person.",
  city: "A large town.",
  class: "A group of students or category.",
  cloud: "A visible mass of water vapor in the sky.",
  coffee: "A drink made from roasted coffee beans.",
  computer: "An electronic device for processing data.",
  country: "A nation with its own government.",
  day: "A period of 24 hours.",
  door: "A movable barrier used to close an entrance.",
  earth: "The planet we live on.",
  edge: "The outer limit of an object.",
  egg: "An oval object laid by birds.",
  energy: "The ability to do work.",
  eye: "The organ used for sight.",
  face: "The front part of the head.",
  fact: "Something known to be true.",
  farm: "Land used for growing crops or raising animals.",
  father: "A male parent.",
  field: "An open area of land.",
  fire: "Combustion producing heat and light.",
  fish: "An animal that lives in water.",
  floor: "The lower surface of a room.",
  food: "Something eaten for nutrition.",
  foot: "The body part used for standing and walking.",
  forest: "A large area covered with trees.",
  friend: "A person you like and trust.",
  game: "An activity with rules for fun.",
  garden: "An area where plants are grown.",
  girl: "A female child.",
  glass: "A hard transparent material.",
  gold: "A valuable yellow metal.",
  group: "A number of people or things together.",
  hair: "Strands growing from the skin.",
  hand: "The body part at the end of the arm.",
  head: "The upper part of the body containing the brain.",
  heart: "The organ that pumps blood.",
  home: "The place where someone lives.",
  horse: "A large animal often used for riding.",
  house: "A building for people to live in.",
  idea: "A thought or suggestion.",
  island: "Land surrounded by water.",
  job: "Paid work.",
  juice: "Liquid extracted from fruits or vegetables.",
  key: "A tool used to open a lock.",
  king: "A male ruler of a kingdom.",
  lake: "A large body of water surrounded by land.",
  land: "The solid surface of the Earth.",
  language: "A system of communication.",
  law: "A rule established by authority.",
  leaf: "A flat green part of a plant.",
  letter: "A written or printed character.",
  life: "The state of being alive.",
  light: "The natural agent that makes vision possible.",
  line: "A long narrow mark.",
  list: "A series of items.",
  love: "A strong feeling of affection.",
  machine: "A device that performs a task.",
  man: "An adult male person.",
  map: "A representation of an area.",
  market: "A place where goods are bought and sold.",
  matter: "Physical substance.",
  milk: "A white liquid produced by mammals.",
  mind: "The part responsible for thoughts and feelings.",
  money: "A medium of exchange.",
  month: "One of the twelve divisions of a year.",
  moon: "The Earth's natural satellite.",
  mother: "A female parent.",
  mountain: "A large natural elevation of land.",
  music: "Sounds arranged to create harmony.",
  name: "A word used to identify someone or something.",
  nation: "A large group of people sharing a country.",
  nature: "The physical world and its phenomena.",
  night: "The period of darkness each day.",
  nose: "The organ used for smelling.",
  note: "A brief written record.",
  number: "A symbol or word representing quantity.",
  object: "A material thing.",
  office: "A place where administrative work is done.",
  oil: "A thick liquid substance.",
  page: "One side of a sheet in a book.",
  paper: "Material used for writing or printing.",
  park: "A public green area.",
  party: "A social gathering.",
  peace: "Freedom from conflict.",
  people: "Human beings collectively.",
  person: "An individual human being.",
  phone: "A device used for communication.",
  picture: "An image or drawing.",
  place: "A particular position or area.",
  plant: "A living organism that grows in soil.",
  power: "The ability to influence or control.",
  problem: "A matter requiring a solution.",
  product: "Something that is made or produced.",
  question: "A sentence asking for information.",
  rain: "Water falling from clouds.",
  river: "A large natural stream of water.",
  road: "A route for travel.",
  rock: "A naturally occurring solid mineral material.",
  room: "A separate area within a building.",
  school: "A place where people learn.",
  sea: "A large body of salt water.",
  season: "One of the four periods of the year.",
  shape: "The form of an object.",
  ship: "A large boat.",
  shirt: "A garment worn on the upper body.",
  shoe: "Footwear.",
  shop: "A place where goods are sold.",
  show: "A performance or display.",
  side: "A surface or position of something.",
  sky: "The space above the Earth.",
  snow: "Frozen water crystals falling from clouds.",
  song: "A piece of music with words.",
  sound: "Something that can be heard.",
  space: "The area beyond Earth's atmosphere or an empty area.",
  star: "A luminous object in space.",
  state: "A condition or political region.",
  stone: "A small piece of rock.",
  street: "A public road in a town or city.",
  sun: "The star at the center of our solar system.",
  table: "A piece of furniture with a flat top.",
  team: "A group working together.",
  text: "Written or printed words.",
  thing: "An object or entity.",
  time: "The progression of events.",
  tree: "A tall plant with a trunk.",
  water: "A clear liquid essential for life.",
  way: "A method or path.",
  weather: "The state of the atmosphere.",
  week: "A period of seven days.",
  wind: "Moving air.",
  window: "An opening fitted with glass.",
  woman: "An adult female person.",
  word: "A unit of language.",
  world: "The Earth and all its inhabitants.",
  year: "A period of twelve months.",
  zoo: "A place where animals are kept for display.",
};

export const brazilianWordsToGuess = {
  agua: "Líquido essencial para a vida.",
  amigo: "Pessoa por quem se tem afeto e confiança.",
  amor: "Sentimento profundo de afeto.",
  animal: "Ser vivo que não é uma planta.",
  arvore: "Planta de grande porte com tronco.",
  aviao: "Veículo usado para transporte aéreo.",
  areia: "Conjunto de pequenos grãos de rocha.",
  arroz: "Cereal muito consumido na alimentação.",
  bola: "Objeto redondo usado em jogos.",
  banco: "Instituição financeira ou assento.",
  barco: "Meio de transporte aquático.",
  bebe: "Criança muito pequena.",
  boca: "Parte do rosto usada para comer e falar.",
  bolo: "Doce assado feito de massa.",
  borboleta: "Inseto com asas coloridas.",
  braco: "Membro superior do corpo humano.",
  brisa: "Vento leve e agradável.",
  cachorro: "Animal doméstico muito popular.",
  cafe: "Bebida feita de grãos torrados.",
  cadeira: "Assento para uma pessoa.",
  cama: "Móvel usado para dormir.",
  caminho: "Rota ou direção a seguir.",
  camisa: "Peça de roupa para o tronco.",
  campo: "Área aberta de terreno.",
  caneta: "Objeto usado para escrever.",
  carro: "Veículo motorizado de transporte.",
  carta: "Mensagem escrita enviada a alguém.",
  casa: "Local onde as pessoas moram.",
  castelo: "Grande construção fortificada.",
  ceu: "Espaço visível acima da Terra.",
  chave: "Objeto usado para abrir fechaduras.",
  chuva: "Água que cai das nuvens.",
  cidade: "Grande área urbana.",
  comida: "Tudo aquilo que serve de alimento.",
  computador: "Máquina eletrônica que processa dados.",
  coracao: "Órgão que bombeia sangue.",
  corpo: "Estrutura física de um ser vivo.",
  criança: "Pessoa em fase inicial da vida.",
  dedo: "Parte das mãos ou dos pés.",
  dinheiro: "Meio de troca usado para compras.",
  dente: "Estrutura usada para mastigar.",
  desenho: "Representação feita com linhas.",
  dia: "Período de luz entre amanhecer e anoitecer.",
  escola: "Instituição dedicada ao ensino.",
  escritor: "Pessoa que escreve livros ou textos.",
  espelho: "Superfície que reflete imagens.",
  estrela: "Corpo celeste que emite luz.",
  estrada: "Via usada para deslocamento.",
  familia: "Grupo de pessoas ligadas por parentesco.",
  farol: "Torre ou luz para orientar navegantes.",
  festa: "Evento de celebração.",
  flor: "Parte colorida de muitas plantas.",
  floresta: "Grande área coberta por árvores.",
  fogo: "Combustão que produz calor e luz.",
  folha: "Parte geralmente verde de uma planta.",
  fruta: "Parte comestível produzida por plantas.",
  galinha: "Ave doméstica criada por seus ovos.",
  garagem: "Local onde veículos são guardados.",
  gato: "Pequeno felino domesticado.",
  gelo: "Água em estado sólido.",
  girafa: "Animal alto de pescoço comprido.",
  governo: "Grupo que administra um país.",
  grama: "Planta que cobre o solo.",
  homem: "Pessoa adulta do sexo masculino.",
  hospital: "Local destinado ao tratamento de saúde.",
  hotel: "Estabelecimento para hospedagem.",
  ilha: "Porção de terra cercada por água.",
  imagem: "Representação visual de algo.",
  inverno: "Estação mais fria do ano.",
  jardim: "Área cultivada com plantas e flores.",
  janela: "Abertura em uma parede para entrada de luz.",
  jantar: "Refeição feita à noite.",
  jogo: "Atividade recreativa com regras.",
  jornal: "Publicação com notícias.",
  lago: "Grande quantidade de água cercada por terra.",
  lapis: "Instrumento usado para escrever ou desenhar.",
  leite: "Líquido produzido por mamíferos.",
  leao: "Grande felino conhecido como rei da selva.",
  livro: "Conjunto de páginas encadernadas.",
  loja: "Estabelecimento comercial.",
  lua: "Satélite natural da Terra.",
  luz: "Forma de energia que permite enxergar.",
  madeira: "Material obtido das árvores.",
  mae: "Mulher que tem filhos.",
  mar: "Grande extensão de água salgada.",
  mercado: "Local de compra e venda de produtos.",
  mesa: "Móvel com superfície plana.",
  montanha: "Grande elevação natural do terreno.",
  moeda: "Peça de metal usada como dinheiro.",
  mundo: "O planeta Terra e seus habitantes.",
  musica: "Arte de combinar sons.",
  navio: "Grande embarcação.",
  neve: "Precipitação de cristais de gelo.",
  noite: "Período de escuridão após o pôr do sol.",
  nuvem: "Massa visível de vapor de água.",
  oceano: "Imensa extensão de água salgada.",
  olho: "Órgão responsável pela visão.",
  orelha: "Parte do corpo usada para ouvir.",
  ouro: "Metal precioso de cor amarela.",
  ovo: "Estrutura produzida por aves.",
  pai: "Homem que tem filhos.",
  pais: "Território com governo próprio.",
  papel: "Material usado para escrever ou imprimir.",
  parque: "Área pública de lazer.",
  parede: "Estrutura vertical de uma construção.",
  pato: "Ave aquática de bico largo.",
  pedra: "Fragmento sólido de rocha.",
  peixe: "Animal que vive na água.",
  pessoa: "Ser humano individual.",
  piano: "Instrumento musical de teclas.",
  ponte: "Estrutura usada para atravessar obstáculos.",
  porta: "Abertura que permite entrada e saída.",
  praia: "Faixa de areia junto ao mar.",
  professor: "Pessoa que ensina.",
  queijo: "Alimento produzido a partir do leite.",
  quintal: "Área externa de uma casa.",
  raio: "Descarga elétrica atmosférica.",
  relogio: "Objeto usado para medir o tempo.",
  rio: "Curso natural de água.",
  roupa: "Conjunto de peças usadas para vestir.",
  rua: "Via pública em uma cidade.",
  sala: "Cômodo de uma casa ou edifício.",
  sapato: "Calçado que protege os pés.",
  segredo: "Informação mantida em sigilo.",
  semana: "Período de sete dias.",
  sol: "Estrela no centro do Sistema Solar.",
  sombra: "Área onde a luz é bloqueada.",
  sonho: "Experiência mental durante o sono.",
  sorriso: "Expressão de alegria no rosto.",
  tabela: "Conjunto organizado de dados.",
  telefone: "Aparelho para comunicação à distância.",
  tempo: "Sequência contínua dos acontecimentos.",
  terra: "Solo ou planeta onde vivemos.",
  tesouro: "Bem de grande valor.",
  tigre: "Grande felino de listras.",
  trabalho: "Atividade realizada para produzir algo.",
  trem: "Meio de transporte ferroviário.",
  universidade: "Instituição de ensino superior.",
  vaca: "Animal criado para produção de leite.",
  vento: "Movimento do ar.",
  viagem: "Deslocamento entre lugares.",
  vila: "Pequena comunidade habitada.",
  vinho: "Bebida produzida a partir de uvas.",
  violao: "Instrumento musical de cordas.",
  vizinho: "Pessoa que mora perto.",
  voz: "Som produzido ao falar.",
  zoologico: "Local onde animais são mantidos para exibição.",
};
